author:
  type: Person
  name: Jeppe Hirschberg Jensen
  url: https://jeppejensen.dk/
social:
  links:
    - https://www.linkedin.com/in/jeppehjensen/
title: jeppejensen.dk
tagline: Hi there!
description: I'm Jeppe Hirschberg Jensen, a Digital Advisor with experience as a UX Designer, Product Manager, and Data Strategist. I live in Copenhagen, Denmark, with my amazing (and quite large) family
logo:
show_downloads: false
google_analytics: false
remote_theme: dringtech/jekyll-theme-barebones
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-theme-barebones
